### ISSUE TITLE
3DR Services UI

### ISSUE THREAD

**Issue by phmagic** [DroidPlanner/3DRServices#7]
![3dr-services-03](https://cloud.githubusercontent.com/assets/623864/5387530/6382097e-8090-11e4-993b-3b217b634aad.png)
![3dr-services-02](https://cloud.githubusercontent.com/assets/623864/5387531/6392752a-8090-11e4-90fa-a4bb9ec1c45d.png)
![3dr-services-01](https://cloud.githubusercontent.com/assets/623864/5387532/639a7388-8090-11e4-94aa-e3a1ec09924f.png)

**Comment by zumbrunnen** [comment]
I personally find the launcher icon too minimalistic. Every time I open the launcher and see this green triangle, I'm almost shocked and wonder "what the heck have I installed there?!?".. :scream_cat: 

Can't we use something that resembles the DroidPlanner icon? Something like this for example:

![ic_launcher](https://cloud.githubusercontent.com/assets/3499909/5595518/38f119c4-9275-11e4-9299-94babf1848b9.png)

**Comment by ne0fhyk** [comment]
@phmagic any feedback on @zumbrunnen idea?

**Comment by zumbrunnen** [comment]
OK, I understand, super-ugly icon will stay... :unamused:

**Comment by ne0fhyk** [comment]
@zumbrunnen I closed this issue, because there was no development on this end, but if you have a better icon, I'm all for it :D 
The app shows a constant notification when another app is connected to a vehicle through it, so the icon needs to be simple and pleasing so that it doesn't annoy the use by its presence on the status bar.
Also on lollipop+ device, notifications are drawn in [either white or dark gray](https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorNotifications) regardless of the original icon design, so the icon shape needs to be simple and easily memorable since it'll be lacking any color for the user to identify it.

**Comment by zumbrunnen** [comment]
@ne0fhyk :+1:  I'm going to draft something appealing and come back with a suggestion.
